server:
  port: 8007
spring:
  application:
    name: euraka-server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8006/eureka
    register-with-eureka: false
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
